#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#include <stdint.h>

#include "driver/gpio.h"
#include "driver/i2c.h"

#define APP_WIFI_SSID ""
#define APP_WIFI_PASSWORD ""

#define APP_USE_FAKE_SENSOR 1

#define APP_DEFAULT_SETPOINT 26.0f
#define APP_DEFAULT_HYSTERESIS 0.5f
#define APP_DEFAULT_SENSOR_DIFF_ALARM 1.0f
#define APP_ABS_LOW_TEMP_CUTOFF 18.0f
#define APP_ABS_HIGH_TEMP_CUTOFF 34.0f
#define APP_MIN_SETPOINT 20.0f
#define APP_MAX_SETPOINT 32.0f
#define APP_MIN_HYSTERESIS 0.3f
#define APP_MAX_HYSTERESIS 2.0f
#define APP_MIN_SENSOR_DIFF_ALARM 0.3f
#define APP_MAX_SENSOR_DIFF_ALARM 3.0f
#define APP_MIN_VALID_TEMP 10.0f
#define APP_MAX_VALID_TEMP 50.0f
#define APP_MAX_SENSOR_STEP_DELTA 2.5f
#define APP_SENSOR_FILTER_ALPHA 0.35f

#define APP_SAMPLE_INTERVAL_MS 1000
#define APP_SENSOR_POLL_INTERVAL_MS 50
#define APP_DISPLAY_UPDATE_INTERVAL_MS 66
#define APP_BUTTON_SCAN_INTERVAL_MS 20
#define APP_STATUS_LOG_INTERVAL_MS 5000
#define APP_BUZZ_PULSE_MS 120
#define APP_LONG_PRESS_MS 1200
#define APP_FAST_ADJUST_INTERVAL_MS 100
#define APP_WIFI_CONNECT_TIMEOUT_MS 12000
#define APP_WIFI_SAVE_RECONNECT_DELAY_MS 1200
#define APP_WIFI_RETRY_INTERVAL_MS 15000
#define APP_WIFI_AP_RETRY_INTERVAL_MS 60000
#define APP_OUTPUT_STARTUP_INHIBIT_MS 10000
#define APP_SETTINGS_SAVE_DELAY_MS 2000
#define APP_RELAY_STATS_SAVE_DELAY_MS 2000
#define APP_HEAT_MIN_ON_MS 30000
#define APP_COOL_MIN_ON_MS 60000
#define APP_COOL_MIN_OFF_MS 180000
#define APP_SENSOR_FAIL_LIMIT 3
#define APP_SENSOR_RECOVER_VALID_COUNT 2
#define APP_DS18B20_RESOLUTION_BITS 12
#define APP_DS18B20_CONVERSION_MS 760
#define APP_RELAY_WARN_SWITCH_COUNT 100000UL
#define APP_DEFAULT_BUZZER_ENABLED 1

#define APP_WIFI_SSID_MAX_LEN 33
#define APP_WIFI_PASSWORD_MAX_LEN 65
#define APP_WIFI_AP_SSID_MAX_LEN 32
#define APP_IP_TEXT_MAX_LEN 16
#define APP_FAULT_TEXT_MAX_LEN 20
#define APP_EVENT_LOG_SIZE 6
#define APP_EVENT_LOG_TEXT_LEN 96
#define APP_CMD_QUEUE_LEN 8

#define APP_AP_SSID_PREFIX "FishTankCtrl-Setup"
#define APP_AP_PASSWORD "12345678"

#define APP_RELAY_ACTIVE_LEVEL 0
#define APP_BUZZER_ACTIVE_LEVEL 1

#define APP_I2C_PORT I2C_NUM_0
#define APP_OLED_I2C_ADDRESS 0x3C
#define APP_OLED_DRIVER_SH1106 1

#define PIN_TEMP_A GPIO_NUM_4
#define PIN_TEMP_B GPIO_NUM_16
#define PIN_COOL_CTRL GPIO_NUM_18
#define PIN_HEAT_CTRL GPIO_NUM_19
#if CONFIG_IDF_TARGET_ESP32S3
#define PIN_I2C_SDA GPIO_NUM_8
#define PIN_I2C_SCL GPIO_NUM_9
#define PIN_BUZZ_CTRL GPIO_NUM_15
#define PIN_KEY_SET GPIO_NUM_12
#define PIN_KEY_UP GPIO_NUM_13
#define PIN_KEY_DOWN GPIO_NUM_14
#else
#define PIN_I2C_SDA GPIO_NUM_21
#define PIN_I2C_SCL GPIO_NUM_22
#define PIN_BUZZ_CTRL GPIO_NUM_23
#define PIN_KEY_SET GPIO_NUM_25
#define PIN_KEY_UP GPIO_NUM_26
#define PIN_KEY_DOWN GPIO_NUM_27
#endif

#endif
